### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by ghost**
I think it's a good idea to add this one to bower. The only part I don't know is versioning. How do you version this repo ?

### CODE REVIEW

**Comment by kontur** [comment]
Seems useful! +1

**Comment by jadb** [comment]
:+1:

**Comment by kellysutton** [comment]
Sorry I've been so out of the loop. Merging.

**Comment by mrpollo** [comment]
**FYI** I added jquery.typer to the bower registry

```
☁  Src [master] ⚡ bower search typer
Search results:

    doctype-flexie git://github.com/doctyper/flexie.git
    Typertext git://github.com/terribleplan/Typertext.git
    typeright git://github.com/mediastuttgart/typeright
    symbol-typer git://github.com/eloone/bower-symbol-typer.git
    jquery.typer git://github.com/layervault/jquery.typer.js.git
```

You can unregister following this link http://bower.io/docs/creating-packages/#unregister if you don't think it should be there

**Pull request merged**
